# Generated by Django 5.0.3 on 2024-03-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect_detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectclassification',
            name='max_width',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='defectclassification',
            name='severity',
            field=models.CharField(default='No Defect', max_length=50),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='classification',
            field=models.CharField(max_length=255),
        ),
    ]
