# Generated by Django 5.0.3 on 2024-03-31 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect_detection_app', '0002_defectclassification_max_width_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectclassification',
            old_name='max_width',
            new_name='maximum_width',
        ),
    ]
